### ISSUE TITLE
Gzip not Enabled on cloudfront CDN

### ISSUE THREAD

**Issue by Rkallenkoot** [basscss/basscss.github.io#4]
Hi!

Not sure this is anything you can / should fix, but I thought I'd mention it.
Gzip is not enabled for the CDN link you provide [here](http://www.basscss.com/docs/)

Came to my attention running [webpagetest](http://www.webpagetest.org) and [Checkgzipcompression](http://checkgzipcompression.com/?url=http%3A%2F%2Fd2v52k3cl9vedd.cloudfront.net%2Fbasscss%2F7.0.0%2Fbasscss.min.css)

Sidenote:
Cheers for basscss and the awesome Documentation

**Comment by jxnblk** [comment]
Yeah, I did have that working at some point, but S3 can be confusing. I'll
look into it again.

On Wed, Jul 15, 2015 at 8:53 PM, Roelof Kallenkoot <notifications@github.com
