### ISSUE TITLE
UI Elements guide references deprecated button sizes

### ISSUE THREAD

**Issue by mainej** [basscss/basscss.github.io#9]
The UI Elements guide references the deprecated button size helpers `.button-big`, `.button-narrow` and `.button-small`.  This occurs both in the Button Sizes section, and in many other sections.  As such, many of the examples are broken.

**Comment by jxnblk** [comment]
The button sizes are still available as an optional module, but I need to make note of that in the guides. http://www.basscss.com/docs/optional-modules/
